= Parameters

The parent key for all of the following parameters is `openshift4_logging`.

See the https://docs.openshift.com/container-platform/latest/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying[OpenShift docs] for details.


== `namespace`

[horizontal]
type:: string
default:: `openshift-logging`

The namespace in which to install the operator.


== `channel`

[horizontal]
type:: string
default:: `stable`

Channel of the operator subscription to use.
In OpenShift 4.7 Red Hat introduced an OpenShift version independent logging stack starting with the version 5.0.
Since version 5.1 there are two channels stable and stable-5.x.
Choosing the stable channel allows never have to care about the interoperability as the specific OpenShift version delivers the right version via the operator marketplace.

See the https://docs.openshift.com/container-platform/latest/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying[OpenShift documentation] for details.


== `clusterLogging`

[horizontal]
type:: dictionary
default:: see `defaults.yml`

A dictionary holding the `.spec` for cluster logging.

See the https://docs.openshift.com/container-platform/latest/logging/config/cluster-logging-configuring-cr.html[OpenShift docs] for available parameters.


== `clusterLogForwarding`

=== `clusterLogForwarding.enabled`

[horizontal]
type:: boolean
default:: `false`

Enables log forwarding for the cluster.

=== `clusterLogForwarding.forwarders`

[horizontal]
type:: dictionary
default:: {}

Each key in this dictionary holds the parameters for an `.spec.outputs` object.

See the https://docs.openshift.com/container-platform/latest/logging/cluster-logging-external.html[OpenShift docs] for available parameters.

=== `clusterLogForwarding.namespaces`

[horizontal]
type:: dictionary
default:: {}

Customization for the logging of a specified namespace.

[source,yaml]
----
clusterLogging:
  namespaces:
    my-project: <1>
      forwarder: splunk-forwarder <2>
----

<1> Namespace to configure.
<2> Name of the forwarder defined in `clusterLogForwarding.forwarder`.


== Example

[source,yaml]
----
clusterLogging:
  logStore:
    retentionPolicy:
      application:
        maxAge: 15d
    elasticsearch:
      nodeCount: 5

clusterLogForwarding:
  enabled: true
  forwarders:
    splunk-forwarder:
      secret:
        name: splunk-forwarder
      type: fluentdForward
      url: tls://splunk-forwarder:24224
  namespaces:
    my-project:
      forwarder: splunk-forwarder
----
