= Parameters

The parent key for all of the following parameters is `openshift4_logging`.

See the https://docs.openshift.com/container-platform/latest/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying[OpenShift docs] for details.


== `namespace`

[horizontal]
type:: string
default:: `openshift-logging`

The namespace in which to install the operator.


== `version`

[horizontal]
type:: string
default:: `5.4`

The logging stack version to deploy.
This parameter is used in the default values for parameters `channel` and `alerts`.

We recommend that you use this parameter to specify the logging stack version which the component should deploy.
However, you can still parameters `channel` and `alerts` directly.

See the https://access.redhat.com/support/policy/updates/openshift#logging[OpenShift Logging life cycle documentation] for supported versions of the logging stack.
We recommend that you select a version of the logging stack that's officially listed as compatible with your OpenShift version.

== `channel`

[horizontal]
type:: string
default:: `stable-${openshift4_logging:version}`

Channel of the operator subscription to use.
If you specify the logging stack version through parameter `version`, you shouldn't need to modify this parameter.

In OpenShift 4.7, RedHat decoupled the logging stack version from the OpenShift version.
The decoupled logging stack versions start at version 5.0.
With version 5.1 of the logging stack, channels for specific minor versions were introduced.

Ideally we would just default to the `stable` channel, as that channel will always be backed by a logging stack version compatible with the OpenShift cluster version by the OpenShift marketplace operator.
However, since there's potential for changes in configuration between logging stack versions which need to be managed through the component, we default to using the `stable-5.x` channel matching the version specified in parameter `version`.

See the https://docs.openshift.com/container-platform/latest/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying[OpenShift documentation] for details.

== `alerts`

[horizontal]
type:: string
default:: `release-${openshift4_logging:version}`

Release version of the alerting rules.
If you specify the logging stack version through parameter `version`, you shouldn't need to modify this parameter.

Generally, the value for parameter `alerts` should match the value for parameter `channel`: if you specify `channel: stable-5.4`, you should use `alerts: release-5.4`.

== `kibana_host`

[horizontal]
type:: string
default:: `null`
example:: `kibana.apps.cluster.syn.tools`

Host name of the Kibana route.


== `predict_elasticsearch_storage_alert`

[horizontal]
type:: dict
example::
+
[source,yaml]
----
predict_elasticsearch_storage_alert:
  enabled: true
  lookback_range: 72h
  predict_hours_from_now: 72
  threshold: 85
  for: 6h
  severity: warning
----

Create an alert `SYN_ElasticsearchExpectNodeToReachDiskWatermark` if the storage allocated for Elasticsearch is predicted to reach the low storage watermark.

=== `predict_elasticsearch_storage_alert.enabled`

[horizontal]
type:: boolean
default:: `true`

Enable or disable this alert.

=== `predict_elasticsearch_storage_alert.lookback_range`

[horizontal]
type:: prometheus duration
default:: `72h`

How for to look back to calculate the prediction.


=== `predict_elasticsearch_storage_alert.predict_hours_from_now`

[horizontal]
type:: number
default:: `72`

How far in the future the prediction is calculated.


=== `predict_elasticsearch_storage_alert.threshold`

[horizontal]
type:: number
default:: `85`

The threshold for the alert.
Percentage of disk fill.


=== `predict_elasticsearch_storage_alert.for`

[horizontal]
type:: prometheus duration
default:: `6h`

The alert is firing once the threshold has been reached for this long.


=== `predict_elasticsearch_storage_alert.severity`

[horizontal]
type:: string
default:: `warning`

The severity of the fired alert.


== `ignore_alerts`

[horizontal]
type:: list
default:: []

This parameter can be used to disable alerts provided by openshift cluster-logging-operator.
The component supports removing entries in this parameter by providing the entry prefixed with `~`.

== `monitoring`

This parameter allows users to enable the component's monitoring configuration.
Currently the component has support for deploying custom `ServiceMonitors` on clusters which use component `prometheus` to manage a custom monitoring stack.

=== `enabled`

[horizontal]
type:: boolean
default:: `true`

Whether to deploy monitoring configurations.
If this parameter is set to `true`, the component will check whether component `prometheus` is present on the cluster.
If the component is missing, no configurations will be deployed regardless of the value of this parameter.

=== `instance`

[horizontal]
type:: string
default:: `null`

This parameter can be used to indicate which custom Prometheus instance should pick up the configurations managed by the component.

If the parameter is set to `null`, the default instance configured for component `prometheus` will be used.

=== `enableServiceMonitors`

[horizontal]
type:: dictionary
default:: https://github.com/appuio/component-openshift4-logging/blob/master/class/defaults.yml[See `class/defaults.yml`]

A dictionary with the names of service monitors as keys and booleans as the value.
Can be used to selectively enable or disable service monitors.

== `clusterLogging`

[horizontal]
type:: dictionary
default:: see `defaults.yml`

A dictionary holding the `.spec` for cluster logging.

See the https://docs.openshift.com/container-platform/latest/logging/config/cluster-logging-configuring-cr.html[OpenShift docs] for available parameters.


== `clusterLogForwarding`

=== `clusterLogForwarding.enabled`

[horizontal]
type:: boolean
default:: `false`

Enables log forwarding for the cluster.

=== `clusterLogForwarding.forwarders`

[horizontal]
type:: dictionary
default:: {}

Each key in this dictionary holds the parameters for an `.spec.outputs` object.

See the https://docs.openshift.com/container-platform/latest/logging/cluster-logging-external.html[OpenShift docs] for available parameters.

=== `clusterLogForwarding.namespace_groups`

[horizontal]
type:: dictionary
default:: {}

Customization for the logging of a specified group of namespaces.

Enabling forwarders will send the logs of the specified namespaces to a third-party log aggregator.
For some log aggregation systems you may need to deploy a separate log forwarder.

Enable json parsing for a 'namespace_group' only makes sense if the logs are forwarded to the clusters default elasticsearch instance. Therefor 'default' will automatically be added to the forwarders.

[source,yaml]
----
clusterLogForwarding:
  namespace_groups:
    my-group: <1>
      namespaces: <2>
        - my-namespace
      forwarders: <3>
        - splunk-forwarder
      json: true <4>
----

<1> Namespace to configure.
<2> List of namespaces.
<3> List of forwarders (defined in `clusterLogForwarding.forwarders`).
<4> Enable json logging only for defined namespaces.


=== `clusterLogForwarding.application_logs`

[horizontal]
type:: dictionary
default:: {}

Customization for the logging of all applications.

Enabling forwarders will send the logs of all namespaces to a third-party log aggregator.
For some log aggregation systems you may need to deploy a separate log forwarder.

[source,yaml]
----
clusterLogForwarding:
  application_logs:
    forwarders: <1>
      - splunk-forwarder
    json: true <2>
----

<1> List of forwarders (defined in `clusterLogForwarding.forwarders`).
<2> Enable json logging for all applications.


=== `clusterLogForwarding.infrastructure_logs`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
clusterLogForwarding:
  infrastructure_logs:
    enabled: true
----

Customization for the logging of `openshift*`, `kube*`, or `default` projects.

Enabled by default.

Enabling forwarders will send the logs of all namespaces to a third-party log aggregator.
For some log aggregation systems you may need to deploy a separate log forwarder.

[source,yaml]
----
clusterLogForwarding:
  infrastructure_logs:
    forwarders: <1>
      - splunk-forwarder
    json: true <2>
----

<1> List of forwarders (defined in `clusterLogForwarding.forwarders`).
<2> Enable json logging for all applications.


=== `clusterLogForwarding.audit_logs`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
clusterLogForwarding:
  audit_logs:
    enabled: false
----

Customization for the logging of https://docs.openshift.com/container-platform/latest/security/audit-log-policy-config.html[audit logs].

Disabled by default.

Enabling forwarders will send the logs of all namespaces to a third-party log aggregator.
For some log aggregation systems you may need to deploy a separate log forwarder.

[source,yaml]
----
clusterLogForwarding:
  audit_logs:
    forwarders: <1>
      - splunk-forwarder
    json: true <2>
----

<1> List of forwarders (defined in `clusterLogForwarding.forwarders`).
<2> Enable json logging for all applications.


=== `clusterLogForwarding.json`

[horizontal]
type:: dictionary
default:: see below

Setting `json.enabled` is required for json parsing to be available. You need to additionally enable it in `clusterLogForwarding.application_logs` or `clusterLogForwarding.namespace_groups`, based on your needs, to actually parse the logs.

[source,yaml]
----
clusterLogForwarding:
  json:
    enabled: false <1>
    typekey: 'kubernetes.labels.logFormat' <2>
    typename: 'nologformat' <3>
----

<1> By default JSON parsing is disabled.
<2> The value of that field, if present, is used to construct the index name.
<3> If `typekey` isn't set or its key isn't present, the value of this field is used to construct the index name.

See the https://docs.openshift.com/container-platform/latest/logging/cluster-logging-enabling-json-logging.html#cluster-logging-configuration-of-json-log-data-for-default-elasticsearch_cluster-logging-enabling-json-logging[OpenShift docs] for a detailed explanation.


== Example

[source,yaml]
----
clusterLogging:
  logStore:
    retentionPolicy:
      application:
        maxAge: 15d
    elasticsearch:
      nodeCount: 5
----

=== Forward logs for all application logs to third-party

[source,yaml]
----
clusterLogForwarding:
  enabled: true
  forwarders:
    splunk-forwarder:
      secret:
        name: splunk-forwarder
      type: fluentdForward
      url: tls://splunk-forwarder:24224
  application_logs:
    forwarders:
      - splunk-forwarder
----

=== Forward logs for certain namespaces to third-party

[source,yaml]
----
clusterLogForwarding:
  enabled: true
  forwarders:
    splunk-forwarder:
      secret:
        name: splunk-forwarder
      type: fluentdForward
      url: tls://splunk-forwarder:24224
  namespace_groups:
    my-group:
      namespaces:
        - my-namespace
      forwarders:
        - splunk-forwarder
----

=== Enable JSON parsing for all application logs

[source,yaml]
----
clusterLogForwarding:
  enabled: true
  application_logs:
    json: true
  json:
    enabled: true
----

=== Enable JSON parsing for certain namespaces

[source,yaml]
----
clusterLogForwarding:
  enabled: true
  namespace_groups:
    my-group:
      namespaces:
        - my-namespace
      json: true
  json:
    enabled: true
----
