= Parameters

The parent key for all of the following parameters is `openshift4_logging`.

See the https://docs.openshift.com/container-platform/latest/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying[OpenShift docs] for details.


== `namespace`

[horizontal]
type:: string
default:: `openshift-logging`

The namespace in which to install the operator.


== `channel`

[horizontal]
type:: string
default:: `stable`

Channel of the operator subscription to use.
In OpenShift 4.7 Red Hat introduced an OpenShift version independent logging stack starting with the version 5.0.
Since version 5.1 there are two channels stable and stable-5.x.
Choosing the stable channel allows never have to care about the interoperability as the specific OpenShift version delivers the right version via the operator marketplace.

See the https://docs.openshift.com/container-platform/latest/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying[OpenShift documentation] for details.


== `clusterLogging`

[horizontal]
type:: dictionary
default:: see `defaults.yml`

A dictionary holding the `.spec` for cluster logging.

See the https://docs.openshift.com/container-platform/latest/logging/config/cluster-logging-configuring-cr.html[OpenShift docs] for available parameters.


== `clusterLogForwarder`

=== `clusterLogForwarder.enabled`

[horizontal]
type:: boolean
default:: `false`

Enables log forwarding for the cluster.

=== `clusterLogForwarder.spec`

[horizontal]
type:: dictionary
default:: see `defaults.yml`

A dictionary holding the `.spec` for log forwarding.

The default configuration ensures, that all the logs are still forwarded to the internal elasticsearch. If adding a log forwarder to the config, make sure that all logs are still getting sent to the internal elastic serach (copy the default pipelines, see example).

See the https://docs.openshift.com/container-platform/latest/logging/cluster-logging-external.html[OpenShift docs] for available parameters.


== Example

[source,yaml]
----
clusterLogging:
  logStore:
    retentionPolicy:
      application:
        maxAge: 15d
    elasticsearch:
      nodeCount: 5

clusterLogForwarding:
  enabled: false
  spec:
    outputs:
      - name: splunk-forwarder
        secret:
          name: splunk-forwarder
        type: fluentdForward
        url: tls://splunk-forwarder:24224
    inputs:
      - name: my-app
        application:
          namespaces:
            - my-project
    pipelines:
      - name: audit-logs
        inputRefs:
          - audit
        outputRefs:
          - default
      - name: infrastructure-logs
        inputRefs:
          - infrastructure
        outputRefs:
          - default
      - name: application-logs
        inputRefs:
          - application
        outputRefs:
          - default
      - name: my-app-logs
        inputRefs:
          - my-app
        outputRefs:
          - splunk-forwarder
----
