= Parameters

The parent key for all of the following parameters is `openshift4_logging`.

See the https://docs.openshift.com/container-platform/latest/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying[OpenShift docs] for details.


== `namespace`

[horizontal]
type:: string
default:: `openshift-logging`

The namespace in which to install the operator.


== `channel`

[horizontal]
type:: string
default:: `stable`

Channel of the operator subscription to use.
In OpenShift 4.7 Red Hat introduced an OpenShift version independent logging stack starting with the version 5.0.
Since version 5.1 there are two channels stable and stable-5.x.
Choosing the stable channel allows never have to care about the interoperability as the specific OpenShift version delivers the right version via the operator marketplace.

See the https://docs.openshift.com/container-platform/latest/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying[OpenShift documentation] for details.

== `alerts`

[horizontal]
type:: string
default:: `master`

Release version of the alerting rules.
Should be adjusted according to the channel: If you specify `channel: stable-5.2` use `alerts: release-5.2`.

== `ignore_alerts`

[horizontal]
type:: list
default:: []

This parameter can be used to disable alerts provided by openshift cluster-logging-operator.
The component supports removing entries in this parameter by providing the entry prefixed with `~`.

== `clusterLogging`

[horizontal]
type:: dictionary
default:: see `defaults.yml`

A dictionary holding the `.spec` for cluster logging.

See the https://docs.openshift.com/container-platform/latest/logging/config/cluster-logging-configuring-cr.html[OpenShift docs] for available parameters.


== `clusterLogForwarding`

=== `clusterLogForwarding.enabled`

[horizontal]
type:: boolean
default:: `false`

Enables log forwarding for the cluster.

=== `clusterLogForwarding.forwarders`

[horizontal]
type:: dictionary
default:: {}

Each key in this dictionary holds the parameters for an `.spec.outputs` object.

See the https://docs.openshift.com/container-platform/latest/logging/cluster-logging-external.html[OpenShift docs] for available parameters.

=== `clusterLogForwarding.namespace_groups`

[horizontal]
type:: dictionary
default:: {}

Customization for the logging of a specified group of namespaces.

Enable forwarders will send the logs of the specified namespaces to a third-party log aggregator. Depending on the need you may need to deploy a separate log forwarder.

Enable json parsing for a 'namespace_group' only makes sense if the logs are forwarded to the clusters default elasticsearch instance. Therefor 'default' will automatically be added to the forwarders.

[source,yaml]
clusterLogForwarding:
  namespace_groups:
    my-group: <1>
      namespaces: <2>
        - my-namespace
      forwarders: <3>
        - splunk-forwarder
      json: true <4>
----

<1> Namespace to configure.
<2> List of namespaces.
<3> List of forwarders (defined in `clusterLogForwarding.forwarders`).
<4> Enable json logging only for defined namespaces.


=== `clusterLogForwarding.application_logs`

[horizontal]
type:: dictionary
default:: {}

Customization for the logging of all applications.

Enable forwarders will send the logs of all namespaces to a third-party log aggregator. Depending on the need you may need to deploy a separate log forwarder.

[source,yaml]
clusterLogForwarding:
  application_logs:
    forwarders: <1>
      - splunk-forwarder
    json: true <2>
----

<1> List of forwarders (defined in `clusterLogForwarding.forwarders`).
<2> Enable json logging for all applications.

=== `clusterLogForwarding.json`

[horizontal]
type:: dictionary
default:: see below

Setting `json.enabled` is required for json parsing to be available. You need to additionally enable it in `clusterLogForwarding.application_logs` or `clusterLogForwarding.namespace_groups`, based on your needs, to actually parse the logs.

[source,yaml]
----
clusterLogForwarding:
  json:
    enabled: false <1>
    typekey: 'kubernetes.labels.logFormat' <2>
    typename: 'nologformat' <3>
----

<1> By default JSON parsing is disabled.
<2> The value of that field, if present, is used to construct the index name.
<3> If `typekey` isn't set or its key isn't present, the value of this field is used to construct the index name.

See the https://docs.openshift.com/container-platform/latest/logging/cluster-logging-enabling-json-logging.html#cluster-logging-configuration-of-json-log-data-for-default-elasticsearch_cluster-logging-enabling-json-logging[OpenShift docs] for a detailed explanation.


== Example

[source,yaml]
----
clusterLogging:
  logStore:
    retentionPolicy:
      application:
        maxAge: 15d
    elasticsearch:
      nodeCount: 5
----

=== Forward logs for all application logs to third-party

[source,yaml]
----
clusterLogForwarding:
  enabled: true
  forwarders:
    splunk-forwarder:
      secret:
        name: splunk-forwarder
      type: fluentdForward
      url: tls://splunk-forwarder:24224
  application_logs:
    forwarders:
      - splunk-forwarder
----

=== Forward logs for certain namespaces to third-party

[source,yaml]
----
clusterLogForwarding:
  enabled: true
  forwarders:
    splunk-forwarder:
      secret:
        name: splunk-forwarder
      type: fluentdForward
      url: tls://splunk-forwarder:24224
  namespace_groups:
    my-group:
      namespaces:
        - my-namespace
      forwarders:
        - splunk-forwarder
----

=== Enable JSON parsing for all application logs

[source,yaml]
----
clusterLogForwarding:
  enabled: true
  application_logs:
    json: true
  json:
    enabled: true
----

=== Enable JSON parsing for certain namespaces

[source,yaml]
----
clusterLogForwarding:
  enabled: true
  namespace_groups:
    my-group:
      namespaces:
        - my-namespace
      json: true
  json:
    enabled: true
----
